### ISSUE TITLE
Process - есть ли код?

### ISSUE THREAD

**Issue by aademid** [NIBugakov/RivegaucheHTTP#5]
Когда у товара несколько вариаций, код его самого лежит в списке с вариациями?
![image](https://github.com/NIBugakov/RivegaucheHTTP/assets/130755894/2624772a-8bbb-4994-b50e-9855c2950e05)

**Comment by NIBugakov** [comment]
![image](https://github.com/NIBugakov/RivegaucheHTTP/assets/159261560/21df7c7a-afb0-419b-a99e-c3946d404594)
