### ISSUE TITLE
Будто тут линк ни к месту - Process

### ISSUE THREAD

**Issue by aademid** [NIBugakov/RivegaucheHTTP#6]
4741beb0-8a7e-4071-ad90-cf260da03a1a

Явная, довольно простая манипуляция с данными, где тебе в любом случае перебирать все строки
Поэтому в подобных случаях я предпочитаю циклы.

К тому же этот линк сломается если таблица будет пустой

Иначе RPA превращается в жесткое программирование)

**Comment by NIBugakov** [comment]
Почему-то ссылка не работает на объект
